### ISSUE TITLE
Auto-GTAP doesn't run when cloned onto new computer

### ISSUE THREAD

**Issue by robirahman** [andre-barbe/Auto-GTAP#13]
I'm trying to run Auto-GTAP on my computer, specifically the productivity-increase-simple example, but can't get it to work. Following the instructions in the readme, I:

1. cloned the current version of the project (latest commit is `6d7ba90`)
2. set the python interpreter to use Python 3.6
3. installed PyYAML 4.2b4
4. set source root to src as shown in #10 
5. set working directory to `examples\productivity-increase-simple`
6. ran `Main.py`

The script raises an error upon running:

`Traceback (most recent call last):
  File "C:/Users/robir/PycharmProjects/Auto-GTAP/Main.py", line 5, in <module>
    config = Ag.CreateConfig("config.yaml")
  File "C:\Users\robir\PycharmProjects\Auto-GTAP\src\AutoGTAP\CreateConfig\CreateConfig.py", line 14, in __init__
    with open(yaml_file_location, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

Process finished with exit code 1`

(I see there is a file called `config.yaml` in `examples\productivity-increase-simple`; not sure if this is the config file that is not being found?)

**Comment by andre-barbe** [comment]
I will take a look. See https://barbelabs.atlassian.net/jira/software/projects/PG/boards/1

**Comment by andre-barbe** [comment]
That is indeed the config file that should be found. Line 14 of "CreateConfig.py" is trying to open that file as read. It's not finding it on your system for some reason.

Why don't you take a look at some of the values of variables like "yaml_file_location" and see what might be the problem? If the working directory is what you say, then it should be able to load then the "open" function should be able to find config.yaml in that directory.
